openapi: 3.1.0
info:
  title: Dyocense Decision Kernel API
  version: 0.1.0
  description: >-
    Phase 1 specification covering compile and optimise endpoints. Subject to
    change as additional capabilities are implemented.
servers:
  - url: http://localhost:8001
    description: Local development gateway (future)
paths:
  /v1/compile:
    post:
      summary: Compile goal into an OPS document
      operationId: compileGoal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompileRequest'
      responses:
        '200':
          description: Successful compilation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompileResponse'
  /v1/optimise:
    post:
      summary: Optimise an OPS document into a SolutionPack
      operationId: optimiseOps
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OptimiseRequest'
      responses:
        '200':
          description: Successful optimisation
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/OptimiseResponse'
  /v1/forecast:
    post:
      summary: Generate forecasts for named series
      operationId: forecastSeries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForecastRequest'
      responses:
        '200':
          description: Generated forecasts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastResponse'
  /v1/explain:
    post:
      summary: Produce narrative explanation for an optimisation result
      operationId: explainSolution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExplainRequest'
      responses:
        '200':
          description: Explanation generated
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/ExplainResponse'
  /v1/policy/evaluate:
    post:
      summary: Evaluate policies for a given OPS document
      operationId: evaluatePolicy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PolicyRequest'
      responses:
        '200':
          description: Policy results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
  /v1/diagnose:
    post:
      summary: Provide diagnostic suggestions for infeasible runs
      operationId: diagnoseRun
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiagnoseRequest'
      responses:
        '200':
          description: Diagnostic suggestions
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/DiagnoseResponse'
  /v1/evidence/log:
    post:
      summary: Persist a decision run artefact
      operationId: logEvidence
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvidenceRecord'
      responses:
        '200':
          description: Acknowledgement of stored artefact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvidenceResponse'
  /v1/evidence/{run_id}:
    get:
      summary: Retrieve a stored decision artefact
      operationId: getEvidence
      parameters:
        - in: path
          name: run_id
          schema:
            type: string
          required: true
          description: Identifier of the decision run
      responses:
        '200':
          description: Stored evidence payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvidenceRecordExtended'
        '404':
          description: Run not found
  /v1/runs:
    post:
      summary: Submit a goal for end-to-end orchestration
      operationId: submitRun
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunRequest'
      responses:
        '202':
          description: Run accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunResponse'
  /v1/runs/{run_id}:
    get:
      summary: Retrieve orchestration status/result
      operationId: getRun
      parameters:
        - in: path
          name: run_id
          schema:
            type: string
          required: true
          description: Run identifier
      responses:
        '200':
          description: Run status payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunStatus'
        '404':
          description: Run not found
    get:
      summary: List orchestration runs
      operationId: listRuns
      responses:
        '200':
          description: Run list response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunList'
  /v1/runs/{run_id}:
  /v1/catalog:
    get:
      summary: List available archetypes, solvers, and connectors
      operationId: listCatalog
      responses:
        '200':
          description: Catalog response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalog'
components:
  schemas:
    CompileRequest:
      type: object
      required:
        - goal
      properties:
        goal:
          type: string
        tenant_id:
          type: string
        project_id:
          type: string
        data_inputs:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
    CompileResponse:
      type: object
      required:
        - ops
      properties:
        ops:
          $ref: '#/components/schemas/OpsDocument'
        schema:
          type: object
    OptimiseRequest:
      type: object
      required:
        - ops
      properties:
        ops:
          $ref: '#/components/schemas/OpsDocument'
        warm_start:
          $ref: '#/components/schemas/SolutionPack'
    OptimiseResponse:
      type: object
      required:
        - solution
      properties:
        solution:
          $ref: '#/components/schemas/SolutionPack'
        schema:
          type: object
    OpsDocument:
      $ref: '../../contracts/schemas/ops.schema.json'
    SolutionPack:
      $ref: '../../contracts/schemas/solution_pack.schema.json'
    ForecastRequest:
      type: object
      required:
        - horizon
      properties:
        horizon:
          type: integer
          minimum: 1
          maximum: 12
        series:
          type: array
          items:
            type: object
            required:
              - name
              - values
            properties:
              name:
                type: string
              values:
                type: array
                items:
                  type: number
         data_sources:
          type: array
          description: External data sources used to hydrate the forecast request.
          items:
            $ref: '#/components/schemas/ForecastDataSource'
    ForecastResponse:
      type: object
      required:
        - generated_at
        - model
        - horizon
        - forecasts
      properties:
        generated_at:
          type: string
          format: date-time
        model:
          type: string
        horizon:
          type: integer
        forecasts:
          type: array
          items:
            type: object
            required:
              - name
              - timestamp
              - point
              - low
              - high
            properties:
              name:
                type: string
              timestamp:
                type: string
                format: date-time
              point:
                type: number
              low:
                type: number
              high:
                type: number
    ExplainRequest:
      type: object
      required:
        - goal
        - solution
      properties:
        goal:
          type: string
        solution:
          $ref: '#/components/schemas/SolutionPack'
        forecasts:
          type: array
          items:
            type: object
    ExplainResponse:
      type: object
      required:
        - generated_at
        - summary
        - highlights
        - what_ifs
      properties:
        generated_at:
          type: string
          format: date-time
        summary:
          type: string
        highlights:
          type: array
          items:
            type: string
        what_ifs:
          type: array
          items:
            type: string
    PolicyRequest:
      type: object
      required:
        - ops
        - tenant_id
      properties:
        ops:
          $ref: '#/components/schemas/OpsDocument'
        tenant_id:
          type: string
    PolicyResponse:
      type: object
      required:
        - evaluated_at
        - verdict
        - checks
      properties:
        evaluated_at:
          type: string
          format: date-time
        verdict:
          type: string
        checks:
          type: array
          items:
            type: object
            required:
              - name
              - status
              - message
            properties:
              name:
                type: string
              status:
                type: string
              message:
                type: string
    DiagnoseRequest:
      type: object
      required:
        - ops
      properties:
        ops:
          $ref: '#/components/schemas/OpsDocument'
        solution:
          $ref: '#/components/schemas/SolutionPack'
    DiagnoseResponse:
      type: object
      required:
        - analysed_at
        - feasibility
        - suggestions
      properties:
        analysed_at:
          type: string
          format: date-time
        feasibility:
          type: string
        suggestions:
          type: array
          items:
            type: object
            required:
              - constraint
              - action
              - rationale
            properties:
              constraint:
                type: string
              action:
                type: string
              rationale:
                type: string
    EvidenceRecord:
      type: object
      required:
        - run_id
        - tenant_id
        - ops
        - solution
        - explanation
      properties:
        run_id:
          type: string
        tenant_id:
          type: string
        ops:
          $ref: '#/components/schemas/OpsDocument'
        solution:
          $ref: '#/components/schemas/SolutionPack'
        explanation:
          $ref: '#/components/schemas/ExplainResponse'
    EvidenceResponse:
      type: object
      required:
        - run_id
        - stored_at
      properties:
        run_id:
          type: string
        stored_at:
          type: string
          format: date-time
    EvidenceRecordExtended:
      allOf:
        - $ref: '#/components/schemas/EvidenceRecord'
        - type: object
          properties:
            stored_at:
              type: string
              format: date-time
    RunRequest:
      type: object
      required:
        - goal
        - archetype_id
      properties:
        goal:
          type: string
        archetype_id:
          type: string
        project_id:
          type: string
        horizon:
          type: integer
          minimum: 1
          maximum: 12
        series:
          type: array
          items:
            $ref: '#/components/schemas/ForecastSeries'
        data_inputs:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
        data_inputs:
          type: object
          additionalProperties:
            type: array
            items:
              type: object

    RunResponse:
      type: object
      required:
        - run_id
        - status
      properties:
        run_id:
          type: string
        status:
          type: string
    RunStatus:
      type: object
      required:
        - run_id
        - status
        - goal
      properties:
        run_id:
          type: string
        status:
          type: string
          enum: [pending, running, completed, failed]
        goal:
          type: string
        archetype_id:
          type: string
          nullable: true
        result:
          type: object
          nullable: true
        error:
          type: string
          nullable: true
    RunList:
      type: object
      required:
        - runs
      properties:
        runs:
          type: array
          items:
            $ref: '#/components/schemas/RunStatus'
    ForecastSeries:
      type: object
      required:
        - name
        - values
      properties:
        name:
          type: string
        values:
          type: array
          items:
            type: number
    Catalog:
      $ref: '../../contracts/schemas/catalog.schema.json'
    ForecastDataSource:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          description: Loader type (csv, minio, google_sheets)
        path:
          type: string
        filepath:
          type: string
        delimiter:
          type: string
        name:
          type: string
        name_column:
          type: string
        value_column:
          type: string
        pivot:
          type: boolean
        index_column:
          type: string
        bucket:
          type: string
        key:
          type: string
        endpoint_url:
          type: string
        access_key:
          type: string
        secret_key:
          type: string
        csv_url:
          type: string
        sheet_id:
          type: string
        gid:
          type: string
