openapi: 3.0.3
info:
  title: Trip Planner API
  version: 0.1.0
  description: Minimal endpoints for trip planning, refinement, and persistence.
servers:
  - url: http://localhost:8001
    description: Kernel API gateway (to be extended)
paths:
  /places/suggest:
    get:
      summary: Suggest places for origin/destination fields
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 20
          required: false
      responses:
        '200':
          description: A list of matching places
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/PlaceRef'
                  count:
                    type: integer
  /trips/plan:
    post:
      summary: Generate a trip plan from inputs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TripRequest'
      responses:
        '200':
          description: Generated TripPlan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TripPlan'
  /trips/{id}:
    get:
      summary: Get a saved/generated plan by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: TripPlan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TripPlan'
  /trips/{id}/refine:
    post:
      summary: Apply a refinement to an existing plan
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanDelta'
      responses:
        '200':
          description: Updated TripPlan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TripPlan'
  /trips/{id}/save:
    post:
      summary: Save the plan to the user's account
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Saved
  /trips/{id}/book:
    post:
      summary: Return booking deep links (stub)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deep links
          content:
            application/json:
              schema:
                type: object
                properties:
                  flights:
                    type: string
                    format: uri
                  hotels:
                    type: string
                    format: uri
components:
  schemas:
    PlaceRef:
      type: object
      required: [id, name, type]
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [city, poi, region, country]
        lat:
          type: number
        lng:
          type: number
    TripRequest:
      $ref: '../schemas/trip_planner.schema.json#/definitions/TripRequest'
    PlanDelta:
      $ref: '../schemas/trip_planner.schema.json#/definitions/PlanDelta'
    TripPlan:
      $ref: '../schemas/trip_planner.schema.json#/definitions/TripPlan'
