version: "3.9"

services:
  kernel:
    volumes:
      - ./kernel:/app/kernel
    command: uvicorn kernel.api:app --host 0.0.0.0 --port 8080 --reload

  api:
    environment:
      PLAN_KERNEL_BASE_URL: http://kernel:8080
      FEEDBACK_KERNEL_BASE_URL: http://kernel:8080
      GOAL_KERNEL_BASE_URL: http://kernel:8080
      GOAL_PLAN_SERVICE_URL: http://api:8000
      FEEDBACK_SCHEDULER_URL: http://api:8000
      NEGOTIATION_PLAN_SERVICE_URL: http://api:8000
      PYTHONPATH: /app
    volumes:
      - ./api:/app/api
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload

  client:
    build:
      context: ./client
      target: dev
      args:
        VITE_API_BASE_URL: http://localhost:8000
    command: npm run dev -- --host 0.0.0.0 --port 3000
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  mongo:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"

  neo4j:
    ports:
      - "7474:7474"
      - "7687:7687"
