version: "3.9"

services:
  redis:
    image: redis:7
    container_name: dyocense-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: dyocense-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5.18
    container_name: dyocense-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/testpassword"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
  mongo_data:
