# =====================================================================
# Loki Configuration for Dyocense v4.0
# =====================================================================
# Purpose: Log aggregation and querying
# Storage: Local filesystem (single-process mode)
# Retention: 30 days
# =====================================================================

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  # Retention period
  retention_period: 720h  # 30 days
  
  # Ingestion limits
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_streams_per_user: 10000
  max_global_streams_per_user: 100000
  
  # Query limits
  max_query_length: 721h
  max_query_lookback: 720h
  max_query_series: 500
  max_query_parallelism: 32
  
  # Per-stream limits
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  
  # Cardinality limits
  max_label_names_per_series: 30
  max_label_value_length: 2048
  max_label_name_length: 1024

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

# Enable query scheduler for better resource management
query_scheduler:
  max_outstanding_requests_per_tenant: 256

# Ruler for alerting (optional)
ruler:
  enable_api: true
  enable_alertmanager_v2: true
  alertmanager_url: http://alertmanager:9093
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  ring:
    kvstore:
      store: inmemory
