# =====================================================================
# Promtail Configuration for Dyocense v4.0
# =====================================================================
# Purpose: Ship logs from Docker containers to Loki
# Sources: Docker container logs, application logs
# =====================================================================

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    timeout: 10s
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 10

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    
    relabel_configs:
      # Extract container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      
      # Extract container image
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      
      # Extract container labels
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      
      # Only collect logs from dyocense containers
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        regex: 'dyocense'
        action: keep
    
    pipeline_stages:
      # Parse JSON logs from FastAPI
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            trace_id: trace_id
            span_id: span_id
            logger: logger
      
      # Extract log level
      - labels:
          level: level
          trace_id: trace_id
      
      # Parse timestamp if available
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      
      # Drop healthcheck logs to reduce noise
      - match:
          selector: '{container="dyocense-kernel"}'
          stages:
            - drop:
                expression: '.*GET /health.*'
                drop_counter_reason: healthcheck

  # System logs (optional)
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
    
    pipeline_stages:
      - match:
          selector: '{job="system"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\S+\s+\S+\s+\S+)\s+(?P<host>\S+)\s+(?P<process>\S+)\[(?P<pid>\d+)\]:\s+(?P<message>.*)$'
            - timestamp:
                source: timestamp
                format: Jan 02 15:04:05
            - labels:
                host: host
                process: process

limits_config:
  readline_rate: 10000
  readline_burst: 20000
  max_streams: 0
