/**
 * AI-Powered Plan Generator
 * Creates actionable weekly/daily tasks from business goals
 */

export interface Goal {
    id: string
    title: string
    description: string
    current: number
    target: number
    unit: string
    category: 'revenue' | 'operations' | 'customer' | 'growth' | 'custom'
    deadline: string
}

export interface Task {
    id: string
    title: string
    description: string
    category: string
    priority: 'high' | 'medium' | 'low'
    completed: boolean
    goalId: string
    dueDate: string
    estimatedHours?: number
    autoGenerated: boolean
}

export interface WeeklyPlan {
    weekStart: string
    weekEnd: string
    tasks: Task[]
    goalId: string
    goalTitle: string
}

/**
 * Generate tasks for a specific goal based on its category and context
 */
export function generateTasksForGoal(goal: Goal, businessContext?: any): Task[] {
    const tasks: Omit<Task, 'id' | 'goalId' | 'dueDate' | 'autoGenerated'>[] = []
    const today = new Date()
    const deadline = new Date(goal.deadline)
    const daysRemaining = Math.ceil((deadline.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
    const weeksRemaining = Math.ceil(daysRemaining / 7)

    // Generate category-specific tasks
    switch (goal.category) {
        case 'revenue':
            tasks.push(...generateRevenueTasks(goal, weeksRemaining))
            break
        case 'customer':
            tasks.push(...generateCustomerTasks(goal, weeksRemaining))
            break
        case 'operations':
            tasks.push(...generateOperationsTasks(goal, weeksRemaining))
            break
        case 'growth':
            tasks.push(...generateGrowthTasks(goal, weeksRemaining))
            break
        default:
            tasks.push(...generateGenericTasks(goal, weeksRemaining))
    }

    // Assign due dates and IDs
    return tasks.map((task, index) => ({
        ...task,
        id: `${goal.id}-task-${index + 1}`,
        goalId: goal.id,
        dueDate: addDays(today, Math.floor((index + 1) * (daysRemaining / tasks.length))).toISOString().split('T')[0],
        autoGenerated: true,
    }))
}

/**
 * Revenue-focused tasks
 */
function generateRevenueTasks(goal: Goal, weeks: number): Omit<Task, 'id' | 'goalId' | 'dueDate' | 'autoGenerated'>[] {
    const gap = goal.target - goal.current
    const weeklyTarget = gap / weeks

    return [
        {
            title: 'Analyze current revenue streams',
            description: `Review which products/services contribute most to revenue. Identify top 3 revenue drivers.`,
            category: 'Analytics',
            priority: 'high',
            completed: false,
            estimatedHours: 2,
        },
        {
            title: `Launch promotional campaign`,
            description: `Create and launch a promotion targeting ${(weeklyTarget * 0.3).toFixed(0)} ${goal.unit} in new sales. Focus on high-margin products.`,
            category: 'Marketing',
            priority: 'high',
            completed: false,
            estimatedHours: 4,
        },
        {
            title: 'Reach out to dormant customers',
            description: `Email or call customers who haven't purchased in 60+ days. Offer exclusive discount to win them back.`,
            category: 'Sales',
            priority: 'medium',
            completed: false,
            estimatedHours: 3,
        },
        {
            title: 'Upsell existing customers',
            description: `Review recent orders. Identify 10 customers to upsell complementary products or premium tiers.`,
            category: 'Sales',
            priority: 'medium',
            completed: false,
            estimatedHours: 2,
        },
        {
            title: 'Optimize pricing strategy',
            description: `Review competitor pricing. Test price increase on top 3 products or bundle offers.`,
            category: 'Strategy',
            priority: 'medium',
            completed: false,
            estimatedHours: 3,
        },
        {
            title: 'Review weekly revenue progress',
            description: `Check dashboard metrics. Adjust tactics if not on track for weekly target of ${weeklyTarget.toFixed(0)} ${goal.unit}.`,
            category: 'Analytics',
            priority: 'high',
            completed: false,
            estimatedHours: 1,
        },
    ]
}

/**
 * Customer-focused tasks
 */
function generateCustomerTasks(goal: Goal, weeks: number): Omit<Task, 'id' | 'goalId' | 'dueDate' | 'autoGenerated'>[] {
    return [
        {
            title: 'Build customer loyalty program',
            description: `Design rewards program: points for purchases, referrals, reviews. Set up in your e-commerce platform.`,
            category: 'Marketing',
            priority: 'high',
            completed: false,
            estimatedHours: 5,
        },
        {
            title: 'Send personalized follow-up emails',
            description: `Email recent customers thanking them and offering 10% discount on next purchase. Personalize with product recommendations.`,
            category: 'Marketing',
            priority: 'high',
            completed: false,
            estimatedHours: 2,
        },
        {
            title: 'Improve customer support response time',
            description: `Set up auto-responders. Train team on quick issue resolution. Target <2 hour response time.`,
            category: 'Operations',
            priority: 'medium',
            completed: false,
            estimatedHours: 3,
        },
        {
            title: 'Collect customer feedback',
            description: `Send NPS survey to last 100 customers. Identify pain points and improvement opportunities.`,
            category: 'Customer Success',
            priority: 'medium',
            completed: false,
            estimatedHours: 2,
        },
        {
            title: 'Launch referral program',
            description: `Offer $10 credit to customers who refer friends. Track referrals automatically.`,
            category: 'Marketing',
            priority: 'medium',
            completed: false,
            estimatedHours: 4,
        },
    ]
}

/**
 * Operations-focused tasks
 */
function generateOperationsTasks(goal: Goal, weeks: number): Omit<Task, 'id' | 'goalId' | 'dueDate' | 'autoGenerated'>[] {
    return [
        {
            title: 'Audit current inventory levels',
            description: `Review all SKUs. Identify slow-moving items (turnover <2x/year) and overstocked products.`,
            category: 'Operations',
            priority: 'high',
            completed: false,
            estimatedHours: 3,
        },
        {
            title: 'Negotiate supplier terms',
            description: `Contact top 3 suppliers. Request better payment terms (Net 60) or bulk discounts to improve cash flow.`,
            category: 'Finance',
            priority: 'high',
            completed: false,
            estimatedHours: 4,
        },
        {
            title: 'Implement just-in-time ordering',
            description: `Set up reorder points for top 20 products. Automate purchase orders when stock hits threshold.`,
            category: 'Operations',
            priority: 'medium',
            completed: false,
            estimatedHours: 5,
        },
        {
            title: 'Clear slow-moving inventory',
            description: `Run clearance sale on items with <3 months turnover. Bundle with popular products to move faster.`,
            category: 'Sales',
            priority: 'medium',
            completed: false,
            estimatedHours: 3,
        },
        {
            title: 'Review and update fulfillment process',
            description: `Map current order-to-ship workflow. Identify bottlenecks. Target 24-hour fulfillment time.`,
            category: 'Operations',
            priority: 'medium',
            completed: false,
            estimatedHours: 4,
        },
    ]
}

/**
 * Growth-focused tasks
 */
function generateGrowthTasks(goal: Goal, weeks: number): Omit<Task, 'id' | 'goalId' | 'dueDate' | 'autoGenerated'>[] {
    return [
        {
            title: 'Research new market opportunities',
            description: `Analyze adjacent markets or customer segments. Identify 3 potential expansion opportunities.`,
            category: 'Strategy',
            priority: 'high',
            completed: false,
            estimatedHours: 4,
        },
        {
            title: 'Launch new product/service',
            description: `Based on customer requests and market research, introduce 1 new product line or service offering.`,
            category: 'Product',
            priority: 'high',
            completed: false,
            estimatedHours: 8,
        },
        {
            title: 'Build strategic partnerships',
            description: `Reach out to 5 complementary businesses. Explore co-marketing or bundled offering opportunities.`,
            category: 'Business Development',
            priority: 'medium',
            completed: false,
            estimatedHours: 5,
        },
        {
            title: 'Optimize digital presence',
            description: `Update website SEO. Improve Google My Business listing. Launch social media campaign.`,
            category: 'Marketing',
            priority: 'medium',
            completed: false,
            estimatedHours: 6,
        },
        {
            title: 'Attend industry networking event',
            description: `Find and attend 1 trade show, conference, or local business meetup. Make 10 new contacts.`,
            category: 'Networking',
            priority: 'low',
            completed: false,
            estimatedHours: 8,
        },
    ]
}

/**
 * Generic tasks for custom goals
 */
function generateGenericTasks(goal: Goal, weeks: number): Omit<Task, 'id' | 'goalId' | 'dueDate' | 'autoGenerated'>[] {
    return [
        {
            title: `Break down "${goal.title}" into smaller milestones`,
            description: `Define 3-5 measurable milestones between current (${goal.current}) and target (${goal.target}).`,
            category: 'Planning',
            priority: 'high',
            completed: false,
            estimatedHours: 2,
        },
        {
            title: 'Identify resources and tools needed',
            description: `List all resources (people, budget, tools, data) required to achieve ${goal.title}.`,
            category: 'Planning',
            priority: 'high',
            completed: false,
            estimatedHours: 1,
        },
        {
            title: 'Create detailed action plan',
            description: `For each milestone, write specific action steps with deadlines and owners.`,
            category: 'Planning',
            priority: 'medium',
            completed: false,
            estimatedHours: 3,
        },
        {
            title: 'Weekly progress review',
            description: `Every week, check progress toward ${goal.target} ${goal.unit}. Adjust plan if falling behind.`,
            category: 'Tracking',
            priority: 'high',
            completed: false,
            estimatedHours: 1,
        },
    ]
}

/**
 * Generate complete weekly plan for a goal
 */
export function generateWeeklyPlan(goal: Goal, weekOffset: number = 0): WeeklyPlan {
    const today = new Date()
    const weekStart = addDays(today, weekOffset * 7 - today.getDay())
    const weekEnd = addDays(weekStart, 6)

    const allTasks = generateTasksForGoal(goal)

    // Filter tasks for this week based on due dates
    const weekTasks = allTasks.filter((task) => {
        const dueDate = new Date(task.dueDate)
        return dueDate >= weekStart && dueDate <= weekEnd
    })

    return {
        weekStart: weekStart.toISOString().split('T')[0],
        weekEnd: weekEnd.toISOString().split('T')[0],
        tasks: weekTasks,
        goalId: goal.id,
        goalTitle: goal.title,
    }
}

/**
 * Generate plans for all active goals
 */
export function generateMultiGoalWeeklyPlan(goals: Goal[], weekOffset: number = 0): WeeklyPlan[] {
    return goals.map((goal) => generateWeeklyPlan(goal, weekOffset))
}

/**
 * Utility: Add days to date
 */
function addDays(date: Date, days: number): Date {
    const result = new Date(date)
    result.setDate(result.getDate() + days)
    return result
}

/**
 * Smart task prioritization based on deadline urgency and goal progress
 */
export function prioritizeTasks(tasks: Task[], goals: Goal[]): Task[] {
    return tasks.sort((a, b) => {
        // Get associated goals
        const goalA = goals.find((g) => g.id === a.goalId)
        const goalB = goals.find((g) => g.id === b.goalId)

        // Priority score calculation
        let scoreA = 0
        let scoreB = 0

        // Factor 1: Task priority
        const priorityWeight = { high: 3, medium: 2, low: 1 }
        scoreA += priorityWeight[a.priority]
        scoreB += priorityWeight[b.priority]

        // Factor 2: Goal deadline urgency
        if (goalA) {
            const daysLeftA = Math.ceil((new Date(goalA.deadline).getTime() - Date.now()) / (1000 * 60 * 60 * 24))
            if (daysLeftA < 7) scoreA += 3
            else if (daysLeftA < 14) scoreA += 2
            else if (daysLeftA < 30) scoreA += 1
        }

        if (goalB) {
            const daysLeftB = Math.ceil((new Date(goalB.deadline).getTime() - Date.now()) / (1000 * 60 * 60 * 24))
            if (daysLeftB < 7) scoreB += 3
            else if (daysLeftB < 14) scoreB += 2
            else if (daysLeftB < 30) scoreB += 1
        }

        // Factor 3: Goal progress (prioritize goals that are behind)
        if (goalA) {
            const progressA = (goalA.current / goalA.target) * 100
            if (progressA < 25) scoreA += 2
            else if (progressA < 50) scoreA += 1
        }

        if (goalB) {
            const progressB = (goalB.current / goalB.target) * 100
            if (progressB < 25) scoreB += 2
            else if (progressB < 50) scoreB += 1
        }

        return scoreB - scoreA // Higher score = higher priority
    })
}
