"""initial_schema

Revision ID: f8a82d1a01e2
Revises: 
Create Date: 2025-11-14 14:28:04.554497+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f8a82d1a01e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_benchmarks',
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('benchmark_id')
    )
    op.create_index('idx_benchmarks_industry', 'external_benchmarks', ['industry'], unique=False)
    op.create_index('idx_benchmarks_source_metric', 'external_benchmarks', ['source', 'metric_name'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('api_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('api_token')
    )
    op.create_index('idx_tenants_plan_tier', 'tenants', ['plan_tier'], unique=False)
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_table('business_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index('idx_metrics_name', 'business_metrics', ['metric_name'], unique=False)
    op.create_index('idx_metrics_tenant_timestamp', 'business_metrics', ['tenant_id', sa.text('timestamp DESC')], unique=False)
    op.create_table('data_sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('sync_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index('idx_datasources_tenant', 'data_sources', ['tenant_id'], unique=False)
    op.create_index('idx_datasources_type', 'data_sources', ['connector_type'], unique=False)
    op.create_table('evidence_graph',
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_metric', sa.String(length=255), nullable=False),
    sa.Column('target_metric', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index('idx_evidence_source', 'evidence_graph', ['source_metric'], unique=False)
    op.create_index('idx_evidence_target', 'evidence_graph', ['target_metric'], unique=False)
    op.create_index('idx_evidence_tenant', 'evidence_graph', ['tenant_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accuracy_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index('idx_forecasts_created', 'forecasts', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_forecasts_tenant_metric', 'forecasts', ['tenant_id', 'metric_name'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('problem_type', sa.String(length=100), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solver_status', sa.String(length=100), nullable=True),
    sa.Column('solve_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_optimization_created', 'optimization_runs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_optimization_tenant_type', 'optimization_runs', ['tenant_id', 'problem_type'], unique=False)
    op.create_table('smart_goals',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('parent_goal_id', sa.UUID(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['smart_goals.goal_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_index('idx_goals_status', 'smart_goals', ['status'], unique=False)
    op.create_index('idx_goals_tenant_id', 'smart_goals', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_user_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('coaching_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_coaching_tenant_user', 'coaching_sessions', ['tenant_id', 'user_id'], unique=False)
    op.create_index('idx_coaching_updated', 'coaching_sessions', [sa.text('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_coaching_updated', table_name='coaching_sessions')
    op.drop_index('idx_coaching_tenant_user', table_name='coaching_sessions')
    op.drop_table('coaching_sessions')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_goals_tenant_id', table_name='smart_goals')
    op.drop_index('idx_goals_status', table_name='smart_goals')
    op.drop_table('smart_goals')
    op.drop_index('idx_optimization_tenant_type', table_name='optimization_runs')
    op.drop_index('idx_optimization_created', table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index('idx_forecasts_tenant_metric', table_name='forecasts')
    op.drop_index('idx_forecasts_created', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('idx_evidence_tenant', table_name='evidence_graph')
    op.drop_index('idx_evidence_target', table_name='evidence_graph')
    op.drop_index('idx_evidence_source', table_name='evidence_graph')
    op.drop_table('evidence_graph')
    op.drop_index('idx_datasources_type', table_name='data_sources')
    op.drop_index('idx_datasources_tenant', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index('idx_metrics_tenant_timestamp', table_name='business_metrics')
    op.drop_index('idx_metrics_name', table_name='business_metrics')
    op.drop_table('business_metrics')
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_index('idx_tenants_plan_tier', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('idx_benchmarks_source_metric', table_name='external_benchmarks')
    op.drop_index('idx_benchmarks_industry', table_name='external_benchmarks')
    op.drop_table('external_benchmarks')
    # ### end Alembic commands ###
