import { Menu, Download, Share2, HelpCircle, History, Sparkles } from "lucide-react";

interface HeaderProps {
  title: string;
  onOpenDrawer: () => void;
  onOpenExport: () => void;
  onNewPlaybook?: () => void;
}

export const Header = ({ title, onOpenDrawer, onOpenExport, onNewPlaybook }: HeaderProps) => {
  return (
    <header className="bg-white border-b shadow-sm">
      <div className="max-w-full px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <button
            onClick={onOpenDrawer}
            className="p-2 rounded-lg border border-gray-200 hover:bg-gray-50"
            aria-label="Open plan drawer"
          >
            <Menu size={18} />
          </button>
          <div>
            <h1 className="text-lg font-semibold text-gray-900">{title}</h1>
            <p className="text-xs text-gray-500">Generated by Dyocense Copilot</p>
          </div>
        </div>
        <nav className="flex items-center gap-3 text-sm text-gray-600">
          <button className="flex items-center gap-1 px-3 py-2 rounded-lg border border-gray-200 hover:bg-gray-50">
            <HelpCircle size={16} /> Give feedback
          </button>
          {onNewPlaybook && (
            <button
              className="flex items-center gap-1 px-3 py-2 rounded-lg border border-primary text-primary hover:bg-blue-50"
              onClick={onNewPlaybook}
            >
              <Sparkles size={16} /> New playbook
            </button>
          )}
          <button className="flex items-center gap-1 px-3 py-2 rounded-lg border border-gray-200 hover:bg-gray-50">
            <History size={16} /> Run history
          </button>
          <button
            onClick={onOpenExport}
            className="flex items-center gap-1 px-3 py-2 rounded-lg border border-gray-200 hover:bg-gray-50"
          >
            <Download size={16} /> Export
          </button>
          <button className="flex items-center gap-1 px-3 py-2 rounded-lg border border-gray-200 hover:bg-gray-50">
            <Share2 size={16} /> Share
          </button>
        </nav>
      </div>
    </header>
  );
};
