"""Connector marketplace catalog metadata."""

CONNECTOR_CATALOG = [
    {
        "id": "google-drive",
        "name": "google-drive",
        "displayName": "Google Drive",
        "category": "storage",
        "icon": "FileText",
        "dataTypes": ["sales", "inventory", "customers", "finances", "documents"],
        "authType": "oauth2",
        "region": "Global",
    },
    {
        "id": "xero",
        "name": "xero",
        "displayName": "Xero Accounting",
        "category": "finance",
        "icon": "DollarSign",
        "dataTypes": ["invoices", "expenses", "customers", "suppliers", "accounts"],
        "authType": "oauth2",
        "region": "UK",
    },
    {
        "id": "sage",
        "name": "sage",
        "displayName": "Sage Accounting",
        "category": "finance",
        "icon": "FileText",
        "dataTypes": ["invoices", "expenses", "customers", "suppliers", "accounts"],
        "authType": "api_key",
        "region": "UK",
    },
    {
        "id": "shopify",
        "name": "shopify",
        "displayName": "Shopify",
        "category": "ecommerce",
        "icon": "ShoppingCart",
        "dataTypes": ["sales", "inventory", "customers", "products"],
        "authType": "oauth2",
        "region": "Global",
    },
    {
        "id": "square",
        "name": "square",
        "displayName": "Square POS",
        "category": "pos",
        "icon": "CreditCard",
        "dataTypes": ["sales", "inventory", "customers", "transactions"],
        "authType": "oauth2",
        "region": "US",
    },
    {
        "id": "quickbooks",
        "name": "quickbooks",
        "displayName": "QuickBooks",
        "category": "finance",
        "icon": "FileText",
        "dataTypes": ["invoices", "expenses", "customers", "suppliers"],
        "authType": "oauth2",
        "region": "US",
    },
    {
        "id": "woocommerce",
        "name": "woocommerce",
        "displayName": "WooCommerce",
        "category": "ecommerce",
        "icon": "ShoppingBag",
        "dataTypes": ["sales", "inventory", "customers", "products"],
        "authType": "api_key",
        "region": "Global",
    },
    {
        "id": "stripe",
        "name": "stripe",
        "displayName": "Stripe",
        "category": "finance",
        "icon": "CreditCard",
        "dataTypes": ["payments", "customers", "subscriptions"],
        "authType": "api_key",
        "region": "Global",
    },
    {
        "id": "hubspot",
        "name": "hubspot",
        "displayName": "HubSpot CRM",
        "category": "crm",
        "icon": "Users",
        "dataTypes": ["leads", "contacts", "deals", "pipeline"],
        "authType": "oauth2",
        "region": "Global",
    },
    {
        "id": "rest-api",
        "name": "rest-api",
        "displayName": "Custom REST API",
        "category": "storage",
        "icon": "Link",
        "dataTypes": ["custom"],
        "authType": "custom",
        "region": "Global",
    },
    {
        "id": "postgres",
        "name": "postgres",
        "displayName": "PostgreSQL",
        "category": "storage",
        "icon": "Database",
        "dataTypes": ["database"],
        "authType": "basic_auth",
        "region": "Global",
    },
]
